package angel.panduro.dev.walletregister.presentation.ui.utils.constance

object Currency {
    val currencyList = listOf(
        "USD",
        "EUR",
        "GBP",
        "JPY",
        "CNY",
        "INR",
        "AUD",
        "CAD",
        "CHF",
        "PEN",
        "MXN",
        "BRL",
        "ARS",
        "CLP",
        "COP",
        "UYU",
        "BOB",
        "VEF",
        "KRW",
        "ZAR",
        "RUB",
        "TRY",
        "SEK",
        "NOK",
        "DKK",
        "NZD",
        "SGD",
        "HKD",
        "PLN",
        "CZK",
        "HUF",
        "THB",
        "MYR",
        "IDR",
        "PHP",
        "EGP",
        "NGN",
        "AED",
        "SAR",
        "ILS",
        "TWD",
        "VND"
    )
}